import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SocketProvider } from "../context/socketContext";
import { NotificationsProvider } from "../context/NotificationsContext";
import NotificationsDropdown from "../components/NotificationsDropdown";
import Chatbot from "../components/Chatbot";

function Header() {
  return (
    <header style={{ 
      display: 'flex', 
      justifyContent: 'space-between', 
      alignItems: 'center',
      padding: '10px 20px', 
      borderBottom: '1px solid #e5e7eb',
      background: '#ffffff',
    }}>
      <NotificationsDropdown />
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocketProvider>
          <NotificationsProvider>
            <Header />
            {children}
            <Chatbot />
          </NotificationsProvider>
        </SocketProvider>
      </body>
    </html>
  );
}

